apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-app-ui
  name: auth-app-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-app-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/assignment-scalable-app-network: "true"
        io.kompose.service: auth-app-ui
    spec:
      containers:
        - image: auth-app-ui:latest
          imagePullPolicy: IfNotPresent
          name: auth-ui
          ports:
            - containerPort: 80
              hostPort: 5000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
