apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: products-service
  name: products-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: products-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/assignment-scalable-app-network: "true"
        io.kompose.service: products-service
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/mfe
            - name: PORT
              value: "3000"
          image: products-service:latest
          imagePullPolicy: IfNotPresent
          name: products-service
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
