apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: shell-app
  name: shell-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shell-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/assignment-scalable-app-network: "true"
        io.kompose.service: shell-app
    spec:
      containers:
        - image: shell-app:latest
          name: shell-ui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              hostPort: 4200
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
